#在application.properties/或者application.yml文件中没有添加数据库配置信息.
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bond_sys?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    maxPoolPreparedStatementPerConnectionSize: 20


  redis:
    database: 0
    host: localhost         # Redis服务器地址
    port: 6379              # Redis服务器连接端口
    password:               # Redis服务器连接密码（默认为空）
    pool:
      max-active: 200       # 连接池最大连接数（使用负值表示没有限制）
      max-idle: 10          # 连接池中的最大空闲连接
      max-wait: -1          # 连接池最大阻塞等待时间（使用负值表示没有限制）
      min-idle: 0           # 连接池中的最小空闲连接
    timeout: 1000           # 连接超时时间（毫秒）



mybatis:
  mapper-locations: ["mapper/*.xml","classpath:/mapper/*.xml"]

mybatis-plus:
  global-config:
    id-type: 1
    logic-delete-field: delFlag
    logic-delete-value: 1
    logic-not-delete-value: 0
  mapper-locations: ["classpath:mapper/*.xml","classpath*:mapper/*/*.xml"]
  configuration:
    type-aliases-package: com.baiyinliang.finance.entity
    jdbc-type-for-null: "null"
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl